title: Sandra Scenery
author: Sandra Madjou Nzokouo
email: sandra.madjou-nzokouo@ocsbstudent.ca
description: This is a website designed to contain and track down all my work. as well as my progress while learning new programming languages.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
